;TRABALHO FINAL DE AC@

#INCLUDE <P16F628A.INC>		;ARQUIVO PADRÃO MICROCHIP PARA 16F628A
__CONFIG H'3F10'


;---------------------- VARIAVEIS ---------------------------------------------------------------------
	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE USUÁRIO

	CONTADOR1		;VARIAVEL DE SUPORTE PARA CONTAGEM DO TEMPO
	CONTADOR2		;VARIAVEL DE SUPORTE PARA CONTAGEM DO TEMPO
	CONTADOR3 		;VARIAVEL DE SUPORTE PARA CONTAGEM DO TEMPO

	BOTAOPRESSIONADO ;VARIAVEL RESPOSAVEL POR EVITAR OVERFLOW DE PILHA DE CHAMADA DE FUNCAO

	ENDC			;FIM DO BLOCO DE MEMÓRIA		


;---------------------- BOTAO ---------------------------------------------------------------------
#DEFINE	BOTAO	PORTA,2	;PORTA DO BOTÃO
					; 0 -> PRESSIONADO
					; 1 -> LIBERADO

;---------------------- DISPLAY LEDS ---------------------------------------------------------------------

#DEFINE	DISPLAYA	PORTB,2	;PORTA DO LED
							; 0 -> APAGADO
							; 1 -> ACESO

#DEFINE	DISPLAYB	PORTB,3	;PORTA DO LED
							; 0 -> APAGADO
							; 1 -> ACESO

#DEFINE	DISPLAYC	PORTB,5	;PORTA DO LED
							; 0 -> APAGADO
							; 1 -> ACESO

#DEFINE	DISPLAYD	PORTB,6	;PORTA DO LED
							; 0 -> APAGADO
							; 1 -> ACESO
#DEFINE	DISPLAYE	PORTB,7	;PORTA DO LED
							; 0 -> APAGADO
							; 1 -> ACESO

#DEFINE	DISPLAYF	PORTB,1	;PORTA DO LED
							; 0 -> APAGADO
							; 1 -> ACESO

#DEFINE	DISPLAYG	PORTB,0	;PORTA DO LED
							; 0 -> APAGADO
							; 1 -> ACESO


;---------------------- CONFIGURACOES INICIAIS ---------------------------------------------------------------------

	ORG	0x00		;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
INICIO
	CLRF	PORTA		;LIMPA O PORTA
	CLRF	PORTB		;LIMPA O PORTB
	BSF STATUS, RP0			;ALTERA PARA O BANCO 1
	MOVLW	B'00000100'
	MOVWF	TRISA		;DEFINE RA2 COMO ENTRADA E DEMAIS COMO SAÍDAS
	CLRF	TRISB		;DEFINE TODO O PORTB COMO SAÍDA
	CLRF	INTCON		;TODAS AS INTERRUPÇÕES DESLIGADAS
	BCF STATUS, RP0 ;RETORNA PARA O BANCO 0
	MOVLW	B'00000111'
	MOVWF	CMCON

;---------------------- LOOP DE CONTAGEM PRINCIPAL ---------------------------------------------------------------------

MAIN
	CALL CLEAR 		;APAGA TODOS OS LEDS

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL ZERO					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 0
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP
	
	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL UM						;LIGA OS LEDS CORRESPONDENTES AO NUMERO 1
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL DOIS					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 2
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL TRES					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 3
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL QUATRO					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 4
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP	

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL CINCO					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 5
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL SEIS					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 6
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL SETE					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 7
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP

	MOVLW 1
	MOVWF BOTAOPRESSIONADO		;BOTAOPRESSIONADO = 1
	CALL OITO					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 8
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
	CALL CLEAR					;APAGA TODOS OS LEDS
	DECFSZ	BOTAOPRESSIONADO	;CASO O BOTAO TENHA SIDO PRESSIONADO ESTA LINHA NAO IRA PULAR
	GOTO MAIN					;E REDIRECIONARA PARA O COMECO DO LOOP

					
	CALL NOVE					;LIGA OS LEDS CORRESPONDENTES AO NUMERO 9
	CALL ATRASO					;EXECUTA UM ATRASO DE 1 SEGUNDO 
								;VERIFICAO DE BOTAO PRESSIONADO DESNECESSARIA POIS A PROXIMA INSTRUCAO JA CHAMAR A MAIN NOVAMENTE
	
	GOTO MAIN					;REINICIA O LOOP


;-------------------------- CONTROLE DO DELAY --------------------------------------



ATRASO	;FUNCAO RESPOSAVEL POR EXECUTAR UM ATRASO DE 1.000020 SEGUNDOS		
	MOVLW	255
	MOVWF	CONTADOR1 	; CONTADOR2 = 255

	MOVLW	34
	MOVWF	CONTADOR2   ; CONTADOR2 = 34
	
	MOVLW	19
	MOVWF	CONTADOR3   ; CONTADOR3 = 6

ATRASO1
	DECFSZ	CONTADOR1	;DECREMENTA ENQUANTO O NUMERO DECREMENTADO NAO FOR IGUAL A ZERO
	GOTO	ATRASO1		;QUANDO DECREMENTADO NOVAMENTE IRA DECREMENTAR ATÉ -256 CAUSANDO UM OVERFLOW E VOLTANDO PARA O VALOR ZERO

	DECFSZ CONTADOR2		;DECREMENTA ENQUANTO O NUMERO DECREMENTADO NAO FOR IGUAL A ZERO
	GOTO ATRASO1			;QUANDO DECREMENTADO NOVAMENTE IRA DECREMENTAR ATÉ -256 CAUSANDO UM OVERFLOW E VOLTANDO PARA O VALOR ZERO

	BTFSS	BOTAO			;EXECUTA UM TESTE A CADA 772uS PARA CONFERIR SE O BOTAO FOI PRESSIONADO	
	GOTO	BOTAO_PRESS		;SE SIM VAI PARA A PARTE DE TRATAMENTO DE BOTAO PRESSIONADO

	MOVLW	34				;CONTADOR 2 = 34
	MOVWF	CONTADOR2   

	DECFSZ CONTADOR3	;DECREMENTA ENQUANTO O NUMERO DECREMENTADO NAO FOR IGUAL A ZERO
	GOTO ATRASO1		;APOS ISSO RETORNA PARA O LOOP PRINCIPAL DANDO CONTINUIDADE A SEQUENCIA

	RETURN				;RETORNA A MAIN

;-------------------------- CONTROLE DO BOTÃO------------------------------------



BOTAO_PRESS		;FUNCAO RESPOSAVEL POR EXECUTAR UM ATRASO DE 3.000214 SEGUNDOS	
	
	MOVLW	255
	MOVWF	CONTADOR1 	; CONTADOR2 = 255

	MOVLW	6
	MOVWF	CONTADOR2   ; CONTADOR2 = 39
	
	MOVLW	10
	MOVWF	CONTADOR3   ; CONTADOR3 = 10

BOTAO_ATRASO
	DECFSZ	CONTADOR1		;DECREMENTA ENQUANTO O NUMERO DECREMENTADO NAO FOR IGUAL A ZERO	
	GOTO	BOTAO_ATRASO	;QUANDO DECREMENTADO NOVAMENTE IRA DECREMENTAR ATÉ -256 CAUSANDO UM OVERFLOW E VOLTANDO PARA O VALOR ZERO
	
	DECFSZ CONTADOR2		;DECREMENTA ENQUANTO O NUMERO DECREMENTADO NAO FOR IGUAL A ZERO	
	GOTO BOTAO_ATRASO		;QUANDO DECREMENTADO NOVAMENTE IRA DECREMENTAR ATÉ -256 CAUSANDO UM OVERFLOW E VOLTANDO PARA O VALOR ZERO

	DECFSZ CONTADOR3		;DECREMENTA ENQUANTO O NUMERO DECREMENTADO NAO FOR IGUAL A ZERO	
	GOTO BOTAO_ATRASO		;QUANDO DECREMENTADO NOVAMENTE IRA DECREMENTAR ATÉ -256 CAUSANDO UM OVERFLOW E VOLTANDO PARA O VALOR ZERO

	MOVLW 200				;BOTAOPRESSIONADO = 200
	MOVWF BOTAOPRESSIONADO	;ISSO IRA FAZER COM QUE NO LOOP PRINCIPAL SEJA REINICIADO O CRONOMETRO
							;ESTE PASSO FOI NECESSARIO POIS SE TROCAR O RETURN DA LINHA DE BAIXO POR UM 'GOTO MAIN'
							;EVENTUALMENTE IRA ATINGIR O STACK OVERFLOW DA PILHA DE CHAMADA DAS FUNCOES

	RETURN					;EXECUTA O RETORNO PARA A FUNCAO MAIN. 
							;PELO FATO DE 'BOTAO_PRESS' TER SIDO CHAMADO COM 'GOTO' AO INVES DE 'CALL', O LOCAL DE RETORNO INSERIDO NA PILHA SERA DA FUNCAO ANTERIOR
							;FORCANDO ASSIM UMA INTERRUPCAO NA FUNCAO DE DELAY, E REINICIANDO A CONTAGEM


;-------------------------- CONTROLE DO DISPLAY ------------------------------------


ZERO				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 0
	BSF DISPLAYA
	BSF DISPLAYB
	BSF DISPLAYC
	BSF DISPLAYD
	BSF DISPLAYE
	BSF DISPLAYF
	RETURN			;RETORNA A MAIN

UM					;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 1
	BSF DISPLAYB
	BSF DISPLAYC
	RETURN			;RETORNA A MAIN

DOIS				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 2
	BSF DISPLAYA
	BSF DISPLAYB
	BSF DISPLAYD
	BSF DISPLAYE
	BSF DISPLAYG
	RETURN

TRES				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 3
	BSF DISPLAYA	
	BSF DISPLAYB
	BSF DISPLAYC	
	BSF DISPLAYD
	BSF DISPLAYG
	RETURN			;RETORNA A MAIN

QUATRO				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 4

	BSF DISPLAYF
	BSF DISPLAYG
	BSF DISPLAYB
	BSF DISPLAYC
	RETURN			;RETORNA A MAIN

CINCO				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 5
	BSF DISPLAYA
	BSF DISPLAYF
	BSF DISPLAYG
	BSF DISPLAYC
	BSF DISPLAYD
	RETURN			;RETORNA A MAIN

SEIS				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 6
	BSF DISPLAYA
	BSF DISPLAYF
	BSF DISPLAYG
	BSF DISPLAYC
	BSF DISPLAYD	
	BSF DISPLAYE		
	RETURN			;RETORNA A MAIN

SETE				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 7
	BSF DISPLAYA
	BSF DISPLAYB
	BSF DISPLAYC
	RETURN			;RETORNA A MAIN

OITO				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 8
	BSF DISPLAYA		
	BSF DISPLAYB
	BSF DISPLAYC
	BSF DISPLAYD
	BSF DISPLAYE
	BSF DISPLAYF
	BSF DISPLAYG
	RETURN			;RETORNA A MAIN

NOVE 				;LIGA AS SAIDAS CORRESPONTENTE AO FORMATO DO DIGITO 9
	BSF DISPLAYA		
	BSF DISPLAYB
	BSF DISPLAYC
	BSF DISPLAYF
	BSF DISPLAYG
	RETURN			;RETORNA A MAIN

CLEAR		;DESLIGA TODAS AS SAIDAS LIGADAS NO DISPLAY
	NOP 	;RECOMENDADO NO DATASHEET A EXECUTAR PELOMENOS UMA INSTRUCAO 
			;ANTES DE ALTERAR O VALOR DE UMA PORTA QUE TENHA SIDO ALTERADA NA INSTRUCAO ANTERIOR

	BCF DISPLAYA
	BCF DISPLAYB
	BCF DISPLAYC
	BCF DISPLAYD
	BCF DISPLAYE
	BCF DISPLAYF
	BCF DISPLAYG

	NOP		;RECOMENDADO NO DATASHEET A EXECUTAR PELOMENOS UMA INSTRUCAO 
			;ANTES DE ALTERAR O VALOR DE UMA PORTA QUE TENHA SIDO ALTERADA NA INSTRUCAO ANTERIOR

	RETURN	;RETORNA A MAIN

	END		;OBRIGATÓRIO
